### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by huntabyte** [Hugos68/svelte-contextify#18]
Love this project! Definitely cleans up context initialization substantially.

One thing I've been trying to implement within my projects is better error handling when context doesn't exist/a way to inform the user that `ComponentX` needs to be a child of `ComponentY`. Currently I'm handling this with a `if (hasContext(SYMBOL))` check inside the context _getter_, and then throwing an error with the name of the component that initialized that context.

So something like `createButtonContext({ ...data}, 'Button')`, and then when someone tries to `getButtonContext` from outside of a `Button`, they get the error telling them that the component should belong to the `Button`, so `getButtonContext("Component I'm currently getting the context in to make errors more comprehendible")` 

Think this may be something worth adding as an optional additional options object arg to the `createContext`?

**Comment by Hugos68** [comment]
That sounds like something worth adding yeah! I could perhaps add a second param that is simply a callback that is called when context is retrieved when it's not set yet, I feel like logging is *too* opinionated, perhaps that person wants to throw or something different, what do you think?

**Comment by huntabyte** [comment]
Money! Love that idea!
