### ISSUE TITLE
Is there a way to manipulate what is passed to the "set" function so we can use derived stores within it?

### ISSUE THREAD

**Issue by saturnonearth** [Hugos68/svelte-contextify#20]
My goal is to add a derived object that uses the Stores that are assigned within the function, to keep everything contained.

Something like this....

```ts
type States = {
 open: Writable<boolean>;
 readable: Writable<boolean>;
 derivedObject: Readable<boolean>;
}

export const [getStates, setStates, key] = createContext<States>();

setStates(() => {
    const open = writable(true);
    const readable = writable(false);
    const derivedObject = derived([open, readable], ([$open, $readable]) => $readable && $open);

    return {
        open,
        readable,
        derivedObject
    }
});
```

**Comment by Hugos68** [comment]
Hey @saturnonearth, I'm not fully understanding the use case here, can't you simply do:

```ts
type States = {
 open: Writable<boolean>;
 readable: Writable<boolean>;
 derivedObject: Readable<boolean>;
}

export const [getStates, setStates, key] = createContext<States>();

const open = writable(true);
const readable = writable(false);
const derivedObject = derived([open, readable], ([$open, $readable]) => $readable && $open);

setStates({ open, readable, derivedObject });
```
It isn't "perfectly" self contained but I don't really see the use case for allowing a function to be passed in, I definitely could add this though if it improves the DX significantly enough.

**Comment by saturnonearth** [comment]
> Hey @saturnonearth, I'm not fully understanding the use case here, can't you simply do:
> 
> ```ts
> type States = {
>  open: Writable<boolean>;
>  readable: Writable<boolean>;
>  derivedObject: Readable<boolean>;
> }
> 
> export const [getStates, setStates, key] = createContext<States>();
> 
> const open = writable(true);
> const readable = writable(false);
> const derivedObject = derived([open, readable], ([$open, $readable]) => $readable && $open);
> 
> setStates({ open, readable, derivedObject });
> ```
> 
> It isn't "perfectly" self contained but I don't really see the use case for allowing a function to be passed in, I definitely could add this though if it improves the DX significantly enough.

Yes this is fine but I was only trying to self contain as to not set any variables to stores outside of setting context. Maybe I am just not fully understanding the "leaking" aspect of SSR and stores though

**Comment by saturnonearth** [comment]
> Hey @saturnonearth, I'm not fully understanding the use case here, can't you simply do:
> 
> ```ts
> type States = {
>  open: Writable<boolean>;
>  readable: Writable<boolean>;
>  derivedObject: Readable<boolean>;
> }
> 
> export const [getStates, setStates, key] = createContext<States>();
> 
> const open = writable(true);
> const readable = writable(false);
> const derivedObject = derived([open, readable], ([$open, $readable]) => $readable && $open);
> 
> setStates({ open, readable, derivedObject });
> ```
> 
> It isn't "perfectly" self contained but I don't really see the use case for allowing a function to be passed in, I definitely could add this though if it improves the DX significantly enough.

Yea you're right that's fine
